site_name: Notes

theme: 
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.sections
    
nav:
  - Home: index.md
  - Front-end:
      - Getting Started: frontend/Getting Started.md
      - HTML: frontend/html/html.md
      - CSS: frontend/css/css.md
      - Javascript: frontend/javascript/javascript.md
      
  - Networking:
      - Getting Started: networking/Getting Started.md
      - Catatan: networking/notes/ccnaintro.md
      - Labs: networking/labs/labs.md
  - Kali Linux:
      - Kali Linux Command: kali/kali.md
  - About:
      - Notes to Reader: about/notes.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
